### PR TITLE
Added functionality for communicating info about the status, to the ui

### PR DESCRIPTION
**Pull request by GVardakis**
A quite primitive approach to the communication between the observer and worker and the client ui. All it does, is from the observer and worker to send a json to the Flask endpoint in the app.py with some information that will be shown to the user in the next step of the implementation. The received json (at the ui side) will be handled inside the notify function of app.py file.
Hint: Should the url used at the observer.py line 160 be inside a variable so that it's more dynamic?

### CODE REVIEW

**Comment by cshields** [comment]
2 things:

First, I'd recommend running `flake8 satnogsclient` and fixing the suggestions (PEP8). Doesn't change the functionality mostly cosmetic.

That said, it throws an error for me when an observation runs:

```
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/satnogsclient-0.2.4-py2.7.egg/satnogsclient/observer/worker.py", line 101, in _communicate_tracking_info
    self.send_to_socket(p, sock)
  File "/usr/local/lib/python2.7/dist-packages/satnogsclient-0.2.4-py2.7.egg/satnogsclient/observer/worker.py", line 136, in send_to_socket
    self.notify_ui(payload)
  File "/usr/local/lib/python2.7/dist-packages/satnogsclient-0.2.4-py2.7.egg/satnogsclient/observer/worker.py", line 122, in notify_ui
    response = requests.post(url, data=json.dumps(payload), headers=headers, verify=False)
NameError: global name 'requests' is not defined
```

**Comment by GVardakis** [comment]
I made the changes you proposed and added the import that was missing,we haven't been able to run an observation scenario to test the corresponding code though - that's why i hadn't noticed the above error you experienced. Should i remove that chunk of code from worker.py for now, or could you check again to see if we're having another error?

**Comment by cshields** [comment]
cool!  I'll try it again later when I'm off work. You can test changes by setting up the client on your dev device against a testing station in network-dev.satnogs.org and schedule observations there that will knowingly produce no data (it's okay for dev).

For now to trick it into thinking there is a rotor set up rotctld.conf just like in the instructions but use `command=/usr/bin/rotctld -m 1 -T 127.0.0.1` which sets it up as a dummy device. Will be merging the hardware radio and fixed station features in to master soon.

**Comment by GVardakis** [comment]
Nice! I run it and it seems ok

**Comment by acinonyx** [comment]
IMHO, this is wrong architecture. The client should provide an interface for someone to get the status and subscribe for events.

**Comment by GVardakis** [comment]
Yes, this was discussed in today's meeting. A solution proposed was that flask (app.py) will somehow query the various objects(observer,worker) that hold the information about the status and display it in the ui. Any other idea is welcome.

**Comment by GVardakis** [comment]
I came up with a new approach for the communication between the ui and the modules (namely the worker which holds most of the necessary information). In this version, a thread is spawned by the worker every time an observation is running which creates a tcp socket listening for connection from the flask endpoint. The flask endpoint (for demonstration reasons this is done in the index endpoint for now) whenever asked, sends a request to the thread with a tcp socket, which then responds with all the information available.

**Comment by cshields** [comment]
Works! Looks like a good start/architecture.

Can we hold on merging this to master until after v0.2.5 goes out (pending one small r?, hopefully within days)? I would like to roll the big UI improvements into a v0.3

v0.2.5 will just be getting hardware radio functionality into pip before hamvention. If we can roll a lot of UI functionality in before hamvention as a v0.3 that would be awesome but I wouldn't block on that like I want to for hardware radios (v0.2.5).

Unrelated to this PR - there's a group of students at valpo.edu using satnogsclient webui as a project to take on - would be good to hand them specific tasks to tackle within a defined set of requirements. Find etihwnad or I on irc for details.

**Comment by GVardakis** [comment]
I added some functionality for getting periodically the upcoming tasks from the network and feeding them to the ui whenever requested. I also think we should hold on merging this to master, since we are close to completing the implementation of the various templates that will render that information. Maybe tomorrow, or in the weekend we will have pushed here the complete and working ui (at least for the status tab)

**Comment by cshields** [comment]
The update_status queries during a satellite observation are rarely getting responses, and queueing up waiting for a response.  Some will work.  See https://www.dropbox.com/s/g4flrvc54erognv/Screenshot%202016-04-16%2012.15.27.png?dl=0

When it does work it seems to update just fine!  Looks good.

**Comment by ctriant** [comment]
@cshields  It's strange because I can't see the behavior that you describe at my laptop (Chrome and Firefox),  although I can confirm it's presence from George. I'll focus on it. Probably it's an issue on the initialization of the json response, that leads to malformed requests.

**Comment by GVardakis** [comment]
The problem with the rare responses is fixed. Now it should work properly

**Comment by cshields** [comment]
works now! I'd also like to point out that for whatever reason the cpu load on a browser running the status page during an active pass is very high (both in firefox and chrome). Its not that bad inbetween passes, but there might be a need to optimize there.

**Comment by GVardakis** [comment]
I see what you mean, but i'm not sure if the excessive cpu use is caused by the latest changes in the ui or if it's a more general problem of the client

**Comment by comzeradd** [comment]
This seems to have many unnecessary merge commits that have to go away before merging.

**Comment by GVardakis** [comment]
It shouldn't be merged yet, but what do you mean that the merge commits should go away? Erase the merge commits?

**Comment by comzeradd** [comment]
Yes, all interim merges in this branch should be fast-forward merges. A commit named "Merge branch 'notify_ui' of https://github.com/GVardakis/satnogs-client" means nothing for the history of the project and should not land on master's log.

**Comment by comzeradd** [comment]
On a related note, most of @nchronas commit messages need rewording to actually describe the change been made.

**Comment by ppapadeas** [comment]
Closing as this work is not merged properly on dev branch

**Pull request closed without merging**
