### PR TITLE
Gnuradio script execution from client

### PR DESCRIPTION
**Pull request by GVardakis**

### CODE REVIEW

**Comment by ppapadeas** [comment]
@adamkalis r?

**Comment by comzeradd** [comment]
We should remove commented python code.

**Comment by GVardakis** [comment]
@ppapadeas or someone else should give me the green light in order to completely delete that block of code, this is why i left it there.

**Comment by acinonyx** [comment]
Use imperative in commit messages. Also 'Gnuradio flowgraph execution' commit message does not describe anything about the change.

**Pull request merged**
