### PR TITLE
Manual observation support

### PR DESCRIPTION
**Pull request by ctriant**
This PR introduces the ability of scheduling an observation manually from the UI.
Relates to #206 and #207.

### CODE REVIEW

**Comment by cshields** [comment]
I tried this out, couple of things:

There is no feedback after pressing "Schedule Observation"..  So I pressed it a couple of times which caused an error in the backend as the same ID was attempted multiple times, causing an exception in the thread and the thread dying.

It is noted that the times are in UTC, when scheduling a manual observation I put what I assumed was UTC, but when it hit the log the observation was +5 hours from what I entered in to the client, so the client assumed my local time zone and there was a conversion done at some point?

Also, you should preface the filename with "receiving_satnogs_<id>" to avoid a possible bug in post_data where if the filename does not begin with receiving it will be assumed that it is a parsable filename with _ as a separator. 

Otherwise, the job did make it in and ran successfully!

**Comment by cshields** [comment]
Oh, one more suggestion, we go ahead and expose the webui externally with this change (see #220):

in /bin/satnogs-poller change the socketio.run line to: 
`
socketio.run(app, host='0.0.0.0')
`

**Comment by ppapadeas** [comment]
After some testing:
* Timeframe on UTC on scheduled jobs
* Instead of Frequency/Mode there should be a drop-down of available gr-satnogs flowgraphs with a field for arguments to be passed on them

**Comment by ctriant** [comment]
Rebased and needs review. Should we squash all these chatty commits @ppapadeas @acinonyx ?

**Review by GVardakis — APPROVED** [review]
r+

**Pull request merged**
