### PR TITLE
Manual observation support

### PR DESCRIPTION
**Pull request by ctriant**
- Add manual observation back-end and front-end

### CODE REVIEW

**Comment by GVardakis** [comment]
Resolves issues #206 and #207

**Comment by comzeradd** [comment]
I think there is some short of indendation mismatches on css and js code. You generally use 4 spaces, but some of the changes here are in 2-space indentation.

**Comment by ctriant** [comment]
You are right.
I think issue resolved at 53ee4c7

**Comment by comzeradd** [comment]
Nice! But you should amend your old commits to fix indentation issues, instead of adding a new commit.

**Comment by ctriant** [comment]
Yeah, I had a little debate in my mind about this. I assumed it would be better not to blend indentation changes to a more "critical" functionality-inducing commit.

**Comment by ctriant** [comment]
@acinonyx Are you sure this PR should close? I think is valid and it was just in a review-pending state.

**Pull request closed without merging**
