### PR TITLE
Refactor status page

### PR DESCRIPTION
**Pull request by ctriant**

### CODE REVIEW

**Comment by ctriant** [comment]
@ppapadeas  please review

**Comment by ppapadeas** [comment]
@ctriant did you push something new?

**Comment by ctriant** [comment]
@ppapadeas fixes #251 but I think one more issue should be opened. 
Gr-satnogs scripts have different options, so we should handle that case, when spawning gnuradio thread and on UI when tips are shown about the script arguments.

**Comment by acinonyx** [comment]
You are introducing multiple changes in one single mega-commit. This is bad practice and makes reviewing very difficult. The changes should have been split into [atomic commits](https://seesparkbox.com/foundry/atomic_commits_with_git)

Here is a list of changes I quickly noticed which should have been atomically committed:
- Socket.IO listening to all addresses
- Logger class for webapp
- Output of logs to console
- PEP 8 line length fixes
- Configurable script and script arguments
- Periodic post data task
- Change default setting from USRP to rtlsdr

And these are only related to the client core functionality and not the webapp.

Nevertheless, I will approve the pull request since the changes look good! Let's apply the atomic commit guidelines from the next pull request.

**Review by acinonyx — APPROVED** [review]

**Pull request merged**
