### PR TITLE
Enable using hardware radio.

### PR DESCRIPTION
**Pull request by johngian**
- Receiver captures line in connected to radio's output, instead of
  using SDR device.

### CODE REVIEW

**Comment by johngian** [comment]
Hey @cshields can you take a look at this? I tested it in makerfaire but it would be great if you can `r?` this.

**Comment by cshields** [comment]
Sure thing!  Should have my v3 up and running this weekend, will test with a radio.

**Comment by cshields** [comment]
Ok, only had today to work on things..  Good news is my v3 is up and running!   but its too late to take it outside and test, so I'll head out early in the morning and hook it up.  Current plan is to have the raspi on the ground station just do rotctld and then have the client and poller run inside the house next to my radio..  (simulate an outside rotor-only setup)  We'll see if I'm lucky enough to take a lunch break and test.  ;)

**Comment by johngian** [comment]
Hey @cshields, did you manage to test this PR or #76 ?

**Pull request closed without merging**
