### PR TITLE
Switch on and off sequencies are set in env variables

### PR DESCRIPTION
**Pull request by GVardakis**
The two sequences, one for switching comms on and one for switching comms off, are given through environment variables. Each sequence consists of four integers which are given in the form RF_SW_CMD_OFF_1, RF_SW_CMD_OFF_2 etc and RF_SW_CMD_ON_1, RF_SW_CMD_ON_2 etc

### CODE REVIEW

**Comment by ppapadeas** [comment]
Check travis test, possibly needs rebase?

**Comment by GVardakis** [comment]
It's been rebased, there were some flake8 issues that i fixed and some jshint issues that already exist in dev i think

**Comment by ppapadeas** [comment]
I merged fixes on dev. please rebase again.

**Comment by ppapadeas** [comment]
R+

**Comment by comzeradd** [comment]
I think it's best to squash flake8 commits in the future. Especially those that fix errors that were introduced by the initial commit.

**Comment by ppapadeas** [comment]
Already doing it on merge, and @GVardakis is aware.

**Comment by ppapadeas** [comment]
Already doing it on merge, and @GVardakis is aware.

**Pull request merged**
