### PR TITLE
Change waterfall image height to 1600px #231

### PR DESCRIPTION
**Pull request by adamkalis**

### CODE REVIEW

**Comment by acinonyx** [comment]
So, this patch changes the height from 800px to 1600px without requiring to double the data?

**Comment by adamkalis** [comment]
I think the data we generate through gr-satnogs are enough for generating the double height waterfall.

@surligas @ppapadeas any concern?

**Review by acinonyx — APPROVED** [review]
Looks good!

**Comment by adamkalis** [comment]
After an offline discussion data are enough for generating double size waterfall. So I merge this pull request.

**Pull request merged**
